### PR TITLE
Fix unknown database type enum requested

### PR DESCRIPTION
**Pull request by daryledesilva**
Fixes:
```
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
```

### CODE REVIEW

**Comment by Naoray** [comment]
If I understand it correctly you are having trouble using this pkg with MySQL version 5.7, right? Isn't upgrading to MySQL v8 an option?

**Comment by daryledesilva** [comment]
Hello, yes not an option yet. Though flexibility in the package is good right? Or should this logic be moved outside your package and into the one that's calling it instead? Just imagining other users who use mysql versions who can't read enums would have to do the same all the time

**Comment by Naoray** [comment]
Until now no one requested that change. I d rather support the latest version of MySQL, which I am using myself, than add bits and pieces that are added for backwards compatibility.

Could you add that part on your side? If someone else is asking the same thing Again I might change my mind, but until then I would rather not at this.

**Comment by tanthammar** [comment]
@Naoray I need this to. Is it possible to merge this PR?

**Comment by Naoray** [comment]
@tanthammar & @daryledesilva done

**Pull request closed without merging**
